### PR TITLE
Voronoi dev

### PR DESCRIPTION
**Pull request by BrendanParmer**
**Features**
* New voronoi image filter
  * Usage: `$voronoi [points] [seed] [img]`
* Voronoi animation function
  * Usage: `$voronoi_animate [seed] [img]`

### CODE REVIEW

**Comment by Jason717717** [comment]
When given input with seed not integral like `$voronoi 4 absd https://www.cleverfiles.com/howto/wp-content/uploads/2018/03/minion.jpg`, terminal outputs the following error
`seed = int(seed)
ValueError: invalid literal for int() with base 10: 'absd'`

**Comment by Jason717717** [comment]
Also for input with points not integral like `$voronoi aewa 0 https://www.cleverfiles.com/howto/wp-content/uploads/2018/03/minion.jpg`, it gives
`points = int(points)
ValueError: invalid literal for int() with base 10: 'aewa'`

**Comment by Jason717717** [comment]
Complete error message is like
`2023-05-01 20:43:00 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\utils\effect.py", line 129, in command
    points = int(points)
ValueError: invalid literal for int() with base 10: '4.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\cogs\effect_commands.py", line 51, in voronoi
    await process_command(ctx, Voronoi(), *args, points=points, seed=seed)
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\image_utils.py", line 62, in process_command
    await process_url(ctx, args[0], command.command, **kwargs)
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\image_utils.py", line 77, in process_url
    out_path = await func(in_path, **kwargs)
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\utils\effect.py", line 133, in command
    raise BadArgument
discord.ext.commands.errors.BadArgument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 211, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\13544\Desktop\cs 222\Team0-ImageBot\cogs\effect_commands.py", line 58, in voronoi_error_handler
    await ctx.send(error)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\context.py", line 842, in send
    return await super().send(
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 1394, in on_message
    await self.process_commands(message)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 1391, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 1353, in invoke
    await ctx.command.dispatch_error(ctx, exc)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 633, in dispatch_error
    await injected(cog, ctx, error)
  File "C:\Users\13544\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 217, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message`

**Comment by Jason717717** [comment]
The same goes for `$voronoi_animate` when given input with seed not integral like `$voronoi_animate abcd https://www.cleverfiles.com/howto/wp-content/uploads/2018/03/minion.jpg`

**Comment by BrendanParmer** [comment]
Nice catch! Should be resolved now

**Review by Ulico — APPROVED** [review]
Looks good!

**Pull request merged**
