### PR TITLE
Attached images dev

### PR DESCRIPTION
**Pull request by BrendanParmer**
**Features**
* Commands are now able to process image URLs and multiple attached images without separate commands

**Refactor**
* Commands should now use the `process_command` wrapper function, which handles using a provided URL or extracting URLs from attached images
  * To use this, do `await process_command(ctx, [your_func], *args, [any keyword arguments you need])`. The image processing function `your_func` should have `img_path` as its first parameter
* New `process_url` command that takes care of downloading the image, processing it, sending it, and deleting it
* Commands now separated into different modules using cogs for readability, found in the `cogs/` directory
* I've switched the grayscale image sending function to match the other functions by saving to disk first. Not as efficient, but it'll make life a little easier when we start dealing with updating all the functions to upload stuff to Imgur

### CODE REVIEW

**Comment by Jason717717** [comment]
Right now, when shutting down with crtl^c, it gives the following runtime error:
_Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025EC9C183A0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed_
I don't know if this matters, but don't have this before.

**Comment by Jason717717** [comment]
Any commands that end with a bad url like no spacing between last argument and url will result in this response from the bot:
Please send a valid image or URL.
Usage:
    test_image [image_url]
    test_image (and attach an image
Maybe changing the response message would be better.

**Comment by BrendanParmer** [comment]
> Right now, when shutting down with crtl^c, it gives the following runtime error: Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x0000025EC9C183A0> Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in **del** self.close() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close self._loop.call_soon(self._call_connection_lost, None) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 751, in call_soon self._check_closed() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed raise RuntimeError('Event loop is closed') RuntimeError: Event loop is closed I don't know if this matters, but don't have this before.

Sorry about that, unfortunately I don't have a way to test this right now. `Ctrl-C` on Unix-like OSs exits fine without anything. Is it just when you're trying to exit the bot?

**Comment by dsding2** [comment]
I'm getting the same error when shutting down with ctrl+c. I think this is a product of the interrupt not properly cleaning up the callbacks, so it won't affect normal running. That said, it's probably bad practice to just leave it as is.

**Comment by Jason717717** [comment]
> > Right now, when shutting down with crtl^c, it gives the following runtime error: Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x0000025EC9C183A0> Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in **del** self.close() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close self._loop.call_soon(self._call_connection_lost, None) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 751, in call_soon self._check_closed() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed raise RuntimeError('Event loop is closed') RuntimeError: Event loop is closed I don't know if this matters, but don't have this before.
> 
> Sorry about that, unfortunately I don't have a way to test this right now. `Ctrl-C` on Unix-like OSs exits fine without anything. Is it just when you're trying to exit the bot?

Yes.

**Comment by BrendanParmer** [comment]
Didn't mean to merge into main, didn't checkout

**Pull request merged**
